= Demo Setup

== Connecting to Minikube cluster

If you have made a minikube instance available externally, then you can setup your environment to work with that cluster.  There are some pre-requisites though

. You must have ssh access to the machine running minikube (call it `MINIKUBE_HOST`)
. The `MINIKUBE_HOST` needs to have `scp` installed
. You need to have a key pair generated (e.g. from `ssh-keygen`) and have access to both the public and private key
** Public key path is `PUBLIC_KEY_PATH`
** Private key path is `PRIVATE_KEY_PATH`
. You must be able to ssh login as the user who created the minikube cluster on the remote machine (call it `MINIKUBE_USER`)

Once you have satisfied the pre-requisites, here's how you can get access to the cluster

. Copy the public key to the remote machine to allow access using the private key:
+
[.console-input]
[source,bash,subs="attributes+,+macros"]
----
ssh-copy-id -i pass:[${PUBLIC_KEY_PATH}] pass:[${MINIKUBE_USER}@${MINIKUBE_HOST}]
----
+
. Next, run the following command to pull necessary certs and create a suitable kubeconfig
+
[.console-input]
[source,bash,subs="attributes+,+macros"]
----
pass:[${DEMO_HOME}]/scripts/create-kubeconfig.sh pass:[${MINIKUBE_HOST}] pass:[${PRIVATE_KEY_PATH}] pass:[${MINIKUBE_USER}]
----

== Building and deploying the demoapp

To build a new containerized demo app, run the following command:

[.console-input]
[source,bash,subs="attributes+,+macros"]
----
cd pass:[${DEMO_HOME}]/demo/demo-app
mvn -B package -DskipTests \
        -Dquarkus.container-image.build=true \
        -Dquarkus.container-image.push=true \
        -Dquarkus.container-image.registry=quay.io \
        -Dquarkus.container-image.group=mhildenb \
        -Dquarkus.container-image.name=tutorial-operator-demoapp \
        -Dquarkus.jib.base-jvm-image=fabric8/java-alpine-openjdk11-jre \
        -Dquarkus.container-image.username=pass:[${USER}] -Dquarkus.container-image.password=pass:[${PASSWORD}] \
        -Dquarkus.container-image.tag=latest
# Can't use docker container and jib at same time
#        -Dquarkus.docker.dockerfile-jvm-path=src/main/docker/Dockerfile.jvm
----

To deploy the demo-app, run the following command:

[.console-input]
[source,bash,subs="attributes+,+macros"]
----
kubectl apply -f pass:[${DEMO_HOME}]/kube/demo-app/demo-app-deploy.yaml
----

[NOTE]
====
This will deploy to the current context namespace.  Use `-n` parameter to deploy to another namespace
====
