apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: appops.org.mhildenb.operatortutorial
spec:
  group: org.mhildenb.operatortutorial
  versions:
  - name: v1beta1
    # Each version can be enabled/disabled by Served flag.
    served: true
    # One and only one version must be marked as the storage version.
    storage: true
    # Aschema is required
    schema:
      openAPIV3Schema:
        type: object
        properties:
          deploymentLabel:
            type: string
          logging:
            type: object
            properties:
              logThreshold:
                type: string
              logFormat:
                type: string
  scope: Namespaced
  names:
    plural: appops
    singular: appops
    kind: AppOps
    shortNames:
      - appop