apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: appops.org.mhildenb.operatortutorial
spec:
  group: org.mhildenb.operatortutorial
  versions:
  - name: v1beta2
    # Each version can be enabled/disabled by Served flag.
    served: true
    # One and only one version must be marked as the storage version.
    storage: true
    subresources:
      status: { }
    # A schema is required
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              deploymentLabel:
                type: string
              logging:
                type: object
                properties:
                  logThreshold:
                    type: string
                  outstandingRequestThreshold:
                    type: integer
              pods:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    elevatedLogging:
                      type: boolean
          status:
            type: object
            properties:
              message:
                type: string
        required: [spec]
  scope: Namespaced
  names:
    plural: appops
    singular: appops
    kind: AppOps
    shortNames:
      - appop