apiVersion: "org.mhildenb.operatortutorial/v1beta2"
kind: AppOps
metadata:
  name: my-bespoke-app
spec:
  deploymentLabel: demo-app
  logging:
    logThreshold: FATAL
    outstandingRequestThreshold: 2
    #logFormat: "%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c{3.}] [%F] (%t) %s%e%n"