apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: customservices.sample.javaoperatorsdk
spec:
  group: sample.javaoperatorsdk
  version: v1
  scope: Namespaced
  names:
    plural: customservices
    singular: customservice
    kind: CustomService
    shortNames:
      - cs